config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [ :index, :show, :edit, :update] do
    resources :services
    resources :appointments, only: [ :create ]
    resources :pages
    resources :reviews

  end
  get '/appointments/:barber_id/new', to: 'appointments#new', as: :new_appointment
  get '/my_appointments', to: 'appointments#index', as: :my_appointments
  get '/my_services/:barber_id', to: 'services#index', as: :my_services
  resources :reviews

  resources :chatrooms, only: [:show, :create, :new] do
    resources :messages, only: :create
  end
  get '/my_chatrooms', to: 'chatrooms#my_chatrooms', as: :my_chatrooms
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role: {
    client: 0,
    barber: 1
  }

  has_many :reviews, foreign_key: :client_id, class_name: "Review", dependent: :destroy
  has_many :reviews, foreign_key: :barber_id, class_name: "Review", dependent: :destroy

  has_many :sent_messages, foreign_key: :sender_id, class_name: "Message", dependent: :destroy
  has_many :received_messages, foreign_key: :recipient_id, class_name: "Message", dependent: :destroy

  # has_many :chatrooms, through: :received_messages, foreign_key: :recipient_id, class_name: "Message"

  has_many :appointments, foreign_key: :client_id, class_name: "Appointment", dependent: :destroy
  has_many :appointments, foreign_key: :barber_id, class_name: "Appointment", dependent: :destroy

  has_many :services, foreign_key: :barber_id, class_name: 'Service', dependent: :destroy
  has_many :time_slots, foreign_key: :barber_id, class_name: 'TimeSlot', dependent: :destroy

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address, presence: true
  # validates_format_of :phone_number, :with =>  /\d[0-9]\)*\z/ , :message => "Only positive number without spaces are allowed"
  def full_name
    "#{first_name} #{last_name}"
  end

  def average_rating
    return nil if self.reviews.count == 0
    return self.reviews.reduce(0) { |sum, review| sum + review.rating } / self.reviews.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @barbers = User.where(role: "barber")
    # @marker = current_user.geocoded.map({
    #   lat: current_user.latitude,
    #   lng: current_user.longitude
    # })
    if params[:query].present?
      sql_query = "first_name @@ :query OR last_name @@ :query OR address @@ :query OR post_code @@ :query"
      @barbers = User.barber.where(sql_query, query: "%#{params[:query]}%")
      @markers = @barbers.geocoded.map do |barber|
        {
          lat: barber.latitude,
          lng: barber.longitude,
          info_window: render_to_string(partial: "info1_window", locals: { barber: barber })
        }
      end
    else
      @barbers = User.where(role: "barber")
      @markers = @barbers.geocoded.map do |barber|
        {
        lat: barber.latitude,
        lng: barber.longitude,
        info_window: render_to_string(partial: "info1_window", locals: { barber: barber })
        }
      end
    end

    # @markers = @barbers.geocoded.map do |barber|
    #   {
    #     lat: barber.latitude,
    #     lng: barber.longitude,
    #     info_window: render_to_string(partial: "info1_window", locals: { barber: barber })
    #   }
    # end
  end

  def show
    @barber = User.find(params[:id])
    @previous_chat = previous_chat?
    @chatroom = set_chatroom if @previous_chat

    @appointments = @barber.barber? ?
      Appointment.all.where(barber: @barber) :
      Appointment.all.where(client: @barber)

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)

    authorize @user

    if @user.save
      redirect_to edit_user_path, notice: "Your profile has been successfully created"
    else
      render :new
    end
  end

  private

  def previous_chat?
    @messages = Message.where(
      "(sender_id = ? AND recipient_id = ?)
      OR (sender_id = ? AND recipient_id = ?)",
      current_user.id, @barber.id, @barber.id, current_user.id
    )
    @messages.any?
  end

  def set_chatroom
    @messages.first.chatroom
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :role,
      :email,
      :photo,
      :description,
      :address,
      :post_code,
      :phone_number,
      :service,
      :price,
      :duration
    )
  end
end

app/views/users/_info1_window.html.erb
<%= link_to barber do %>
  <div class="barber-avatar">
    <% if barber.photo.attached? %>
      <%= cl_image_tag barber.photo.key %>
    <% else %>
      <%= image_tag "missing.png" %>
    <% end %>
  </div>
  <div class= map_barber>
    <h1> <%= barber.full_name %></h1>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="sign-up-form">
    <h1>Edit Your Profile</h1>

    <%= simple_form_for @user do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>
        <%= f.input :address %>
        <%= f.input :post_code %>
        <%= f.input :phone_number %>
        <%= f.input :description %>
        <%# <%= f.collection_radio_buttons :cut_type, haircut:, beard:, both: %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<!-- Top Banner Titles -->
<div class="banner-title">
  <h1>Clean Kut's</h1>
  <p>Your barber around the corner</p>
</div>
<!-- Search bar -->
<%= render 'shared/searchbar' %>
<!-- Barber section -->
<div class="barbers-container">
  <h2>We found <%=@barbers.count %> barbers</h2>
  <div class="barber-cards">
    <% @barbers.each do |barber|%>
      <div class="barber-card">
        <div class="barber-avatar">
          <% if barber.photo.attached? %>
            <%= cl_image_tag barber.photo.key %>
          <% else %>
            <%= image_tag "missing.png" %>
          <% end %>
        </div>
        <div class="barber-infos">
          <div class="d-flex justify-content-between">
            <h3><%= link_to barber.full_name, barber %></h3>
                        <!-- link to chatroom -->
            <% if @chatroom.nil? %>
              <%= link_to new_chatroom_path(recipient_id: barber.id) do %><i class="far fa-comment"></i><% end %>
            <% else %>
              <%= link_to chatroom_path(@chatroom, recipient_id: barber.id) do %><i class="far fa-comment"></i><% end %>
            <% end %>
          </div>
          <div class="barber-location"><i class="fas fa-map-marker-alt"></i><span><%= barber.address %></span></div>
          <p><%= barber.description %></p>
          <div class="mt-1">
            <% barber.average_rating.times do %>
              <i class="fas fa-star "></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div id="map" class="map"
    style="margin-top: 10%; width: 100%; height: 500px; border-radius: 8px; box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.2);"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/users/show.html.erb
<% content_for :meta_title, "#{@barber.full_name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @barber.description %>
<% content_for :meta_image, cl_image_path("https://d15zsgzz0klz55.cloudfront.net/ca/business_placeholders/barbers-e758256ebf4d4360b3f1806d9a737219.barbers") %>
<!-- Barber dashboard -->
<div class="barber-dashboard">
  <div class="barber-profile-card">
    <div class="top-barber-card-info">
      <div class="barber-name">
        <h2><%= @barber.full_name %></h2>
        <%= link_to 'Edit Profile', edit_user_path if current_user == @barber %>
      </div>
      <div class="info-avatar-container">
        <div class="profile-info">
          <div class="phone"><i class="fas fa-phone-alt"></i>
            <%= @barber.phone_number %>
          </div>
          <div class="address"><i class="fas fa-city"></i>
            <%= @barber.address %>
          </div>
          <div class="email"><i class="far fa-envelope"></i>
            <%= @barber.email %>
          </div>
          <div class="icon">
            <div class="barber">
              <% @barber.review.to_i.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          </div>
        </div>
        <div class="barber-avatar-lg">
          <% if @barber.photo.attached? %>
            <div><%= cl_image_tag @barber.photo.key, :class => "photo" %></div>
          <% end %>
        </div>
      </div>
    </div>
    <% if @barber.barber? %>
      <div class="description">
        <h4>About me</h4>
        <div>
          "<%= @barber.description %>"
        </div>
      </div>
    <% end %>
    <%# TEMP LINK TO CREATE or REJOIN CHATROOM - STEPH %>
    <% if @barber.barber? %>
      <div class="d-flex justify-content-between barber-actions">
        <div class="create-chatroom d-flex align-items-center">
          <i class="far fa-comment"></i>

          <% if current_user.barber? %>
            <%= link_to 'My Chats', my_chatrooms_path %>
          <% else %>
            <% if @previous_chat %>
              <%= link_to "Keep chatting", chatroom_path(@chatroom, recipient_id: @barber.id) %>
            <% else %>
              <%= link_to "Chat with #{@barber.first_name.capitalize}", new_chatroom_path(recipient_id: @barber.id) %>
            <% end %>
          <% end %>


        </div>
        <div class="d-flex align-items-center">
          <i class="fas fa-edit"></i><%= link_to "Write a review", new_user_review_path(@barber) %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- button to book an appointment -->
  <% if @barber.barber? %>
    <div class="book-now booking-button">
      <%= link_to "Book Now", new_appointment_path(@barber), class: "btn btn-gradient font-weight-bold" %> <i class="fas fa-calendar-alt"></i>
    </div>
    <!-- tab with reviews and services -->
    <%= render 'shared/tabs_barber_profile' %>
  <% elsif @barber.client?  %>
    <%= render :partial => "shared/tabs_client_profile" %>
  <% end %>
</div>