config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [ :index, :show, :edit, :update] do
    resources :services
    resources :appointments, only: [ :create ]
    resources :pages
    resources :reviews

  end
  get '/appointments/:barber_id/new', to: 'appointments#new', as: :new_appointment
  get '/my_appointments', to: 'appointments#index', as: :my_appointments
  get '/my_services/:barber_id', to: 'services#index', as: :my_services
  resources :reviews

  resources :chatrooms, only: [:show, :create, :new] do
    resources :messages, only: :create
  end
  get '/my_chatrooms', to: 'chatrooms#my_chatrooms', as: :my_chatrooms
end

app/views/shared/_appointment.html.erb
<!-- This is where I can look at appointments if I am a client and or if I am a barber -->
<!-- create the dashboard profile with appointment section as the core of the page  -->
<!-- appointment section -->
<!-- user AS A BARBER -->
<% if current_user.barber? %>
  <div class="schedule-appointment-reviews-services">
    <div class="part1 d-flex">
      <div class="schedule active" id="schedule3">
        <p>Schedule</p>
      </div>
      <div class="appointments" id="appointments3">
        <p>Appointments</p>
      </div>
      <div class="reviews" id="reviews3">
        <p>Reviews</p>
      </div>
      <div class="services" id="services3">
        <p>Services</p>
      </div>
    </div>
    <div class="part2">
      <div class="schedule_section appear" id="spot1">
        <!-- original appointment file -->
        <div class="info">
          <div class="message">
            <h2><MESSAGES></MESSAGES></h2>
          </div>
          <div class="d-flex flexor">
            <div class="owner-section">
              <p>Your Appointment(s)</p>
              <%= @current_user.barber? ? "Your appointments:" : "Your next appointment:" %>
              <% @my_appointments.each do |appointment| %>
                <% other_user = appointment.other_user(current_user) %>
                <li>With:<%= other_user.full_name() %></li>
                On <%= appointment.day %>
                This service will take <%= appointment.durations %>
              <% end %>
            </div>
          </div>
        </div>
        <!-- end original appointment -->
      </div>
      <div class="appointment_section change" id="spot2">
        <p>These are my appointments</p>
      </div>
      <div class="reviews_section change" id="spot3">
        <p>These are my clients' reviews</p>
      </div>
      <div class="services_section change" id="spot4">
        <p>These are the services I offer</p>
      </div>
    </div>
  </div>
  <!-- end of user AS A BARBER -->
  <!-- user AS A CLIENT -->
<% else %>
  <div class="appointments-reviews-favourites"  id="appointments-reviews-favourites">
    <div class="part1 d-flex">
      <div class="appointments active" id="appointments2">
        <p>My Appointments</p>
      </div>
      <div class="reviews" id="reviews2">
        <p>My Reviews</p>
      </div>
    </div>
    <div class="part2">
      <div class="appointments_section appear" id="spot5">
        <!-- ---original appointment file -->
        <div class="info">
          <div class="message">
            <h2><MESSAGES></MESSAGES></h2>
          </div>
          <div class="d-flex flexor">
            <div class="owner-section">
              <h2>Your Appointment(s)</h2>
              <%= @current_user.barber? ? "Your appointments:" : "Your next appointment:" %>
              <% @my_appointments.each do |appointment| %>
                <% other_user = appointment.other_user(current_user) %>
                <li>With:<%= other_user.full_name() %></li>
                On <%= appointment.day %>
                This service will take <%= appointment.durations %>
              <% end %>
            </div>
          </div>
        </div>
        <!-- end original appointments file  -->
      </div>
      <div class="reviews_section change" id="spot6">
        <div class="appointment-review-card">This is my reviews section you can see how picky I am</div>
      </div>
    </div>
    <!-- end of user AS A CLIENT -->
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">  
  <div class="back">
    <%= link_to :back do %><i class="fas fa-chevron-left"></i>
    <% end %>
  </div> 
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>
  <div class="navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "missing.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit my profile",  edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path do %>
            <%= image_tag "missing.png", :class => "default-avatar" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_improved.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/jbox/image/upload/v1635101182/CleanKutsGrayBG_s0ngku.png" %>
  <% end %>
  <div class="annoying">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
      <li class="nav-item">
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Appointments", "#", class: "dropdown-item" %>
            <%= link_to "Edit Profile", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        <% else %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/jerryant/image/upload/v1635029156/development/sd91617g8uyizkd8p6tm6hgvxqdq.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            </div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_reviews.html.erb
<div class="reviews"> Reviews</div>

app/views/shared/_schedule.html.erb
<div class="schedule"> Schedule</div>

app/views/shared/_searchbar.html.erb
<div class="search-container">
  <%# <input type="text" placeholder="Enter your postal code"> %>
  <%= form_tag users_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      id: "search_form",
      # class: "input",
      placeholder: "Enter your postal code"
      %>
  <% end %>
  <div class="search">
  </div>
</div>

app/views/shared/_services.html.erb
<div class="services"> Services</div>

app/views/shared/_tabs_barber_dashboard.html.erb
<div class="schedule-appointment-reviews-services">
  <div class="part1 d-flex">
    <div class="schedule active" id="schedule3">
      <p>Client</p>
    </div>
    <div class="appointments" id="appointments3">
      <p>Appointments</p>
    </div>
    <div class="reviews" id="reviews3">
      <p>Reviews</p>
          <div class="barber">
            <% @barber.comment.each do |comment| %>
            <%= comment %>
          <% end %>
    </div>
    <div class="services" id="services3">
      <p>Services</p>
    </div>
  </div>
  <div class="part2">
    <div class="schedule_section appear" id="spot1">
      <p>This is my schedule</p>
    </div>
    <div class="appointment_section change" id="spot2">
      <p>These are my appointments</p>
    </div>
    <div class="reviews_section change" id="spot3">
      <p>These are my clients' reviews</p>
    </div>
    <div class="services_section change" id="spot4">
      <p>These are the services I offer</p>
    </div>
  </div>
</div>

app/views/shared/_tabs_barber_profile.html.erb
<div class="reviews-services" id="reviews-services">
  <div class="part1 d-flex">
    <div class="reviews active tab" id="reviews">
      Reviews
    </div>
    <div class="services tab" id="services">
      Services
    </div>
  </div>
  <div class="part2">
    <div class="reviews_section appear" id="spot">
      <% @barber.reviews.order('created_at DESC').each do |r| %>
        <div class="review-card">
          <div class="review-info">
            <p><%= r.client.full_name %></p>
            <p><% r.rating.times do %><i class="fas fa-star"></i><% end %></p>
          </div>
          <p>"<%= r.comment %>"</p>
        </div>
      <% end %>
    </div>
    <div class="services_section" id="spot-service">
      <div class="services-container">
        <% @barber.services.each do |service| %>
          <div class="services-card">
            <div class="cut-type">
              <%= image_tag "Scissors.png" %>
              <div>
                <p><%= service.cut_type %></p>
              </div>
            </div>
            <div class="price">
              <%= image_tag "Payment.png" %>
              <div>
                <p>$<%= service.price %>.00</p>
              </div>
            </div>
            <div class="duration">
              <%= image_tag "Clock.png" %>
              <div>
                <p><%= service.duration/60 %> minutes</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tabs_client_profile.html.erb
<div class="appointments-reviews-favourites"  id="appointments-reviews-favourites">
  <div class="part1 d-flex">
    <div class="appointments active" id="appointments2">
      <p>My Appointments</p>
    </div>
    <div class="reviews" id="reviews2">
      <p>My Reviews</p>
    </div>
    <!-- favourites on hold not a priority decided oct28th
     <div class="favourites" id="favourites2">
      <p>My Favourites</p>
    </div> -->
  </div>
  <div class="part2">
    <div class="appointments_section appear" id="spot5">
      <% if @appointments.empty?  %>
        <p>you have no appointment</p>
      <% else %>
        <% @appointments.each_with_index do |appointment, i|%>
          <div class="appointment-review-card">
            Appointment with <%= link_to appointment.barber.full_name, appointment.barber %>
            <div>
              Date: <b><%= appointment.start_time.strftime("%y-%m-%d") %> at <%= appointment.start_time.strftime("%H:%M %p") %></b>
            </div>
            <div>
              Service: <b><%= appointment.service.cut_type.capitalize %></b>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="reviews_section change" id="spot6">
      <div  class="appointment-review-card">This is my reviews section you can see how picky I am</div>
    </div>
    <!-- favourites on hold not a priority decided oct28th
    <!-- <div class="favourites_section change" id="spot7">
      <p>These are my favourite barbers</p>
    </div> -->
  </div>
</div>