config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [ :index, :show, :edit, :update] do
    resources :services
    resources :appointments, only: [ :create ]
    resources :pages
    resources :reviews

  end
  get '/appointments/:barber_id/new', to: 'appointments#new', as: :new_appointment
  get '/my_appointments', to: 'appointments#index', as: :my_appointments
  get '/my_services/:barber_id', to: 'services#index', as: :my_services
  resources :reviews

  resources :chatrooms, only: [:show, :create, :new] do
    resources :messages, only: :create
  end
  get '/my_chatrooms', to: 'chatrooms#my_chatrooms', as: :my_chatrooms
end

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
  
<div class="simple-calendar">
  <div class="d-flex align-items-center justify-content-between">
    <div class="calendar-heading my-2">
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'btn btn-outline-primary' %>
      <span class="calendar-title btn btn-primary"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'btn btn-outline-primary' %>
    </div>
    <%= link_to 'Book Appointment', my_appointments_url, class: 'btn btn-outline-warning' %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(html) && respond_to?(:block_is_html?) && block_is_html?(passed_block) %>
                <% capture_html(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="align-items-center justify-content-between">
    <div class="calendar-heading my-2 fix-table-header">
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'btn btn-outline-primary' %>
      <span class="calendar-title btn btn-primary"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'btn btn-outline-primary' %>
    </div>

  <table class="table table-striped calendar-table">
    <thead>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% date_range.slice(0, 7).each do |day| %>
            <th class="calendar-header"><%= t('date.abbr_day_names')[day.wday] %> <%= day.strftime("%d") %></th>
          <% end %>
        </tr>
    </thead>
      <tbody>
        <% date_range.each_slice(7) do |week| %>
          <tr>
            <% week.each do |day| %>
              <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <% if defined?(html) && respond_to?(:block_is_html?) && block_is_html?(passed_block) %>
                  <% capture_html(day, sorted_events.fetch(day, []), &passed_block) %>
                <% else %>
                  <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
      <% end %>
    </table>
  </div>